base_url = "https://www.profant.eu"
title = "Profant"
description = "Ondřej Profant: IT specialista se zkušenostmi poslance, náměstka ministr pro digitalizaci a Pirát. Bojuji za digitalizaci, svobodu internetu a otevřená data."
default_language = "cs"
generate_feeds = true
feed_limit = 30
compile_sass = true
taxonomies = [
    {name = "categories", feed = true, paginate_by = 10},
    {name = "tags", feed = true, paginate_by = 10},
]

[extra]
author = "Ondřej Profant"
email = "ondrej.profant@pirati.cz"
fediverse_creator = "@keddie@mastodon.pirati.cz"
twitter_username = "ondrej_profant"
github_username = "kedrigern"
facebook_username = "ondrej.profant"
linkedin_username = "ondrej-profant"
mastodon_url = "https://mastodon.pirati.cz/@keddie"
bluesky_url = "https://bsky.app/profile/ondrej-profant.bsky.social"
keywords = "Ondřej Profant, opendata, opensource, piráti"
img = "/assets/img/ondrej-profant.jpg"
matomo_url = "https://matomo.pirati.cz/"
matomo_site_id = "7"

[markdown]
highlight_code = true
insert_anchor_links = "right"
